//
// TestWeaver Generated Tests
//
// Auto-generated by DeeperCore TestWeaver
// File: CustomHelpProviderTests.cs
// Generated: 2025-12-03T21:13:18.550645
//
// These tests cover edge cases and boundary conditions discovered
// through TestWeaver's 5-phase analysis methodology.
//

using System;

public class CustomHelpProviderTests
{
[Fact]
public void LoadEmbeddedFont_WithNonExistentFile_ThrowsFileNotFoundException()
{
    // Arrange
    var settings = new CommandAppSettings(); // Assuming this exists in the NetPace.Console namespace
    var customHelpProvider = new CustomHelpProvider(settings);

    // Act & Assert
    Assert.Throws<FileNotFoundException>(() => 
        customHelpProvider.GetType()
            .GetMethod("LoadEmbeddedFont", BindingFlags.NonPublic | BindingFlags.Static)
            .Invoke(null, new object[] { "non_existent_font.flf" })
    );

[Fact]
public void CustomHelpProvider_WithNonEmptyApplicationName_InitializesCorrectly()
{
    // Arrange
    var settings = new CommandAppSettings
    {
        ApplicationName = "TestApp"
    };

    // Act
    var helpProvider = new CustomHelpProvider(settings);

    // Assert
    Assert.NotNull(helpProvider);
    // We can't directly access the private ApplicationName field, so we'll test the FigletText method
    var font = helpProvider.LoadEmbeddedFont("slant.flf");
    var figletText = helpProvider.FigletText(font, "TestApp");
    Assert.NotNull(figletText);
    Assert.Contains("TestApp", figletText.ToString());
}
