//
// TestWeaver Generated Tests
//
// Auto-generated by DeeperCore TestWeaver
// File: CustomHelpProviderTests.cs
// Generated: 2025-12-03T22:12:44.171182
//
// These tests cover edge cases and boundary conditions discovered
// through TestWeaver's 5-phase analysis methodology.
//

using System;

public class CustomHelpProviderTests
{
[Fact]
public void LoadEmbeddedFont_WithExistingFont_ReturnsValidFigletFont()
{
    // Arrange
    var settings = new CommandAppSettings(); // Assuming this exists in the NetPace.Console namespace
    var customHelpProvider = new CustomHelpProvider(settings);

    // Act
    var method = typeof(CustomHelpProvider).GetMethod("LoadEmbeddedFont", BindingFlags.NonPublic | BindingFlags.Static);
    var figletFont = method.Invoke(null, new object[] { "slant.flf" }) as FigletFont;

    // Assert
    Assert.NotNull(figletFont);
    Assert.IsType<FigletFont>(figletFont);

[Fact]
public void Constructor_SetsApplicationName_FromSettings()
{
    // Arrange
    var mockSettings = new Mock<ICommandAppSettings>();
    string expectedAppName = "TestApp";
    mockSettings.Setup(s => s.ApplicationName).Returns(expectedAppName);

    // Act
    var helpProvider = new CustomHelpProvider(mockSettings.Object);

    // Assert
    Assert.Equal(expectedAppName, helpProvider.GetType().GetField("ApplicationName", BindingFlags.NonPublic | BindingFlags.Instance).GetValue(helpProvider));
}
