//
// TestWeaver Generated Tests
//
// Auto-generated by DeeperCore TestWeaver
// File: DelayProviderStubTests.cs
// Generated: 2025-12-03T22:12:44.172012
//
// These tests cover edge cases and boundary conditions discovered
// through TestWeaver's 5-phase analysis methodology.
//

using System;

public class DelayProviderStubTests
{
[Fact]
public async Task DelayAsync_WithZeroMilliseconds_RecordsZeroDelayAndCompletesImmediately()
{
    // Arrange
    var delayProvider = new DelayProviderStub();

    // Act
    await delayProvider.DelayAsync(0);

    // Assert
    Assert.Single(delayProvider.RequestedDelays);
    Assert.Equal(0, delayProvider.RequestedDelays[0]);
    Assert.Equal(1, delayProvider.DelayCallCount);

[Fact]
public void DelayAsync_MultipleRequests_RecordsCorrectDelays()
{
    // Arrange
    var delayProvider = new DelayProviderStub();
    var expectedDelays = new[] { 100, 200, 300 };

    // Act
    foreach (var delay in expectedDelays)
    {
        delayProvider.DelayAsync(delay).Wait();

    // Assert
    Assert.Equal(expectedDelays.Length, delayProvider.DelayCallCount);
    Assert.Equal(expectedDelays, delayProvider.RequestedDelays);

    // Test Reset
    delayProvider.Reset();
    Assert.Empty(delayProvider.RequestedDelays);
    Assert.Equal(0, delayProvider.DelayCallCount);

[Fact]
public async Task DelayAsync_ZeroMilliseconds_CompletesImmediately()
{
    // Arrange
    var delayProvider = new DelayProviderStub();

    // Act
    await delayProvider.DelayAsync(0);

    // Assert
    Assert.Single(delayProvider.RequestedDelays);
    Assert.Equal(0, delayProvider.RequestedDelays[0]);
    Assert.Equal(1, delayProvider.DelayCallCount);

[Fact]
public async Task DelayAsync_CancellationRequested_ThrowsOperationCanceledException()
{
    // Arrange
    var delayProvider = new DelayProviderStub();
    using var cts = new CancellationTokenSource();
    cts.Cancel(); // Cancel the token immediately

    // Act & Assert
    await Assert.ThrowsAsync<OperationCanceledException>(() => 
        delayProvider.DelayAsync(100, cts.Token)
    );

    Assert.Empty(delayProvider.RequestedDelays);
    Assert.Equal(0, delayProvider.DelayCallCount);

[Fact]
public async Task DelayAsync_CalledMultipleTimes_RecordsAllRequestedDelays()
{
    // Arrange
    var delayProvider = new DelayProviderStub();
    var expectedDelays = new[] { 100, 200, 300 };

    // Act
    foreach (var delay in expectedDelays)
    {
        await delayProvider.DelayAsync(delay);

    // Assert
    Assert.Equal(expectedDelays.Length, delayProvider.DelayCallCount);
    Assert.Equal(expectedDelays, delayProvider.RequestedDelays);
}
