//
// TestWeaver Generated Tests
//
// Auto-generated by DeeperCore TestWeaver
// File: DelayProviderStubTests.cs
// Generated: 2025-12-04T16:34:00.097030
//
// These tests cover edge cases and boundary conditions discovered
// through TestWeaver's 5-phase analysis methodology.
//

using System;

public class DelayProviderStubTests
{
[Fact]
public async Task DelayAsync_WithZeroMilliseconds_CompletesImmediatelyAndRecordsDelay()
{
    // Arrange
    var delayProvider = new DelayProviderStub();

    // Act
    await delayProvider.DelayAsync(0);

    // Assert
    Assert.Single(delayProvider.RequestedDelays, 
        "DelayAsync should record exactly one delay request");
    Assert.Equal(0, delayProvider.RequestedDelays[0], 
        "The recorded delay should be 0 milliseconds");
    Assert.Equal(1, delayProvider.DelayCallCount, 
        "DelayCallCount should be 1 after a single call to DelayAsync");

[Fact]
public async Task DelayAsync_WithNegativeMilliseconds_RecordsNegativeDelay()
{
    // Arrange
    var delayProvider = new DelayProviderStub();
    int negativeDelay = -100;

    // Act
    await delayProvider.DelayAsync(negativeDelay);

    // Assert
    Assert.Single(delayProvider.RequestedDelays);
    Assert.Equal(negativeDelay, delayProvider.RequestedDelays[0]);
    Assert.Equal(1, delayProvider.DelayCallCount);

[Fact]
public async Task DelayAsync_WithVeryLargeMilliseconds_RecordsRequestedDelay()
{
    // Arrange
    var delayProvider = new DelayProviderStub();
    var veryLargeDelay = int.MaxValue;

    // Act
    await delayProvider.DelayAsync(veryLargeDelay);

    // Assert
    Assert.Single(delayProvider.RequestedDelays);
    Assert.Equal(veryLargeDelay, delayProvider.RequestedDelays[0]);
    Assert.Equal(1, delayProvider.DelayCallCount);

[Fact]
public async Task DelayAsync_WithCancelledToken_ThrowsOperationCanceledException()
{
    // Arrange
    var delayProvider = new DelayProviderStub();
    var cancellationTokenSource = new CancellationTokenSource();
    cancellationTokenSource.Cancel(); // Cancel the token before calling DelayAsync

    // Act & Assert
    await Assert.ThrowsAsync<OperationCanceledException>(() => 
        delayProvider.DelayAsync(1000, cancellationTokenSource.Token));

    Assert.Empty(delayProvider.RequestedDelays);
    Assert.Equal(0, delayProvider.DelayCallCount);

[Fact]
public async Task DelayAsync_CalledMultipleTimes_RecordsCorrectDelays()
{
    // Arrange
    var delayProvider = new DelayProviderStub();
    var expectedDelays = new[] { 100, 200, 300 };

    // Act
    foreach (var delay in expectedDelays)
    {
        await delayProvider.DelayAsync(delay);

    // Assert
    Assert.Equal(expectedDelays.Length, delayProvider.DelayCallCount);
    Assert.Equal(expectedDelays, delayProvider.RequestedDelays);

    // Reset and verify
    delayProvider.Reset();
    Assert.Empty(delayProvider.RequestedDelays);
    Assert.Equal(0, delayProvider.DelayCallCount);

[Fact]
public void Reset_ClearsRequestedDelays()
{
    // Arrange
    var delayProvider = new DelayProviderStub();
    delayProvider.DelayAsync(100);
    delayProvider.DelayAsync(200);
    Assert.Equal(2, delayProvider.DelayCallCount);
    Assert.Equal(2, delayProvider.RequestedDelays.Count);

    // Act
    delayProvider.Reset();

    // Assert
    Assert.Empty(delayProvider.RequestedDelays);
    Assert.Equal(0, delayProvider.DelayCallCount);

[Fact]
public async Task DelayAsync_WithNegativeMilliseconds_ShouldRecordNegativeValue()
{
    // Arrange
    var delayProvider = new DelayProviderStub();
    int negativeMilliseconds = -100;

    // Act
    await delayProvider.DelayAsync(negativeMilliseconds);

    // Assert
    Assert.Single(delayProvider.RequestedDelays);
    Assert.Equal(negativeMilliseconds, delayProvider.RequestedDelays[0]);
    Assert.Equal(1, delayProvider.DelayCallCount);

[Fact]
public async Task DelayAsync_WithVeryLargeMilliseconds_RecordsCorrectDelay()
{
    // Arrange
    var delayProvider = new DelayProviderStub();
    int veryLargeDelay = int.MaxValue;

    // Act
    await delayProvider.DelayAsync(veryLargeDelay);

    // Assert
    Assert.Single(delayProvider.RequestedDelays, veryLargeDelay);
    Assert.Equal(1, delayProvider.DelayCallCount);
    Assert.Equal(veryLargeDelay, delayProvider.RequestedDelays[0]);

[Fact]
public async Task DelayAsync_ConcurrentCalls_RecordsAllDelays()
{
    // Arrange
    var delayProvider = new DelayProviderStub();
    var delays = new[] { 100, 200, 300 };
    var tasks = new List<Task>();

    // Act
    foreach (var delay in delays)
    {
        tasks.Add(delayProvider.DelayAsync(delay));

    await Task.WhenAll(tasks);

    // Assert
    Assert.Equal(delays.Length, delayProvider.DelayCallCount);
    Assert.Equal(delays, delayProvider.RequestedDelays);
}
