//
// TestWeaver Generated Tests
//
// Auto-generated by DeeperCore TestWeaver
// File: DelayProviderStubTests.cs
// Generated: 2025-12-04T13:50:26.298761
//
// These tests cover edge cases and boundary conditions discovered
// through TestWeaver's 5-phase analysis methodology.
//

using System;

public class DelayProviderStubTests
{
[Fact]
public void DelayAsync_WithNegativeMilliseconds_RecordsNegativeValue()
{
    // Arrange
    var delayProvider = new DelayProviderStub();
    int negativeMilliseconds = -100;

    // Act
    delayProvider.DelayAsync(negativeMilliseconds);

    // Assert
    Assert.Single(delayProvider.RequestedDelays);
    Assert.Equal(negativeMilliseconds, delayProvider.RequestedDelays[0]);
    Assert.Equal(1, delayProvider.DelayCallCount);

[Fact]
public async Task DelayAsync_CalledMultipleTimes_RecordsAllRequestedDelays()
{
    // Arrange
    var delayProvider = new DelayProviderStub();
    var expectedDelays = new[] { 100, 200, 300 };

    // Act
    foreach (var delay in expectedDelays)
    {
        await delayProvider.DelayAsync(delay);

    // Assert
    Assert.Equal(expectedDelays.Length, delayProvider.DelayCallCount);
    Assert.Equal(expectedDelays, delayProvider.RequestedDelays);

[Fact]
public void Reset_ClearsRequestedDelays()
{
    // Arrange
    var delayProvider = new DelayProviderStub();
    delayProvider.DelayAsync(100).Wait();
    delayProvider.DelayAsync(200).Wait();
    Assert.Equal(2, delayProvider.RequestedDelays.Count);

    // Act
    delayProvider.Reset();

    // Assert
    Assert.Empty(delayProvider.RequestedDelays);
    Assert.Equal(0, delayProvider.DelayCallCount);

[Fact]
public async Task DelayAsync_ConcurrentCalls_RecordsAllDelays()
{
    // Arrange
    var delayProvider = new DelayProviderStub();
    var tasks = new List<Task>();
    var expectedDelays = new List<int> { 100, 200, 300 };

    // Act
    foreach (var delay in expectedDelays)
    {
        tasks.Add(delayProvider.DelayAsync(delay));

    await Task.WhenAll(tasks);

    // Assert
    Assert.Equal(expectedDelays.Count, delayProvider.DelayCallCount);
    Assert.Equal(expectedDelays, delayProvider.RequestedDelays);
}
