//
// TestWeaver Generated Tests
//
// Auto-generated by DeeperCore TestWeaver
// File: IClockTests.cs
// Generated: 2025-12-03T22:12:44.179058
//
// These tests cover edge cases and boundary conditions discovered
// through TestWeaver's 5-phase analysis methodology.
//

using System;

public class IClockTests
{
[Fact]
public void ClockStub_Now_ReturnsFixedDate()
{
    // Arrange
    var clockStub = new ClockStub();
    var expectedDateTime = new DateTime(1980, 1, 1, 10, 5, 0);

    // Act
    var result = clockStub.Now;

    // Assert
    Assert.Equal(expectedDateTime, result);
    Assert.Equal(1980, result.Year);
    Assert.Equal(1, result.Month);
    Assert.Equal(1, result.Day);
    Assert.Equal(10, result.Hour);
    Assert.Equal(5, result.Minute);
    Assert.Equal(0, result.Second);

[Fact]
public void IncrementingClockStub_Now_IncrementsBy5SecondsOnEachCall()
{
    // Arrange
    var clock = new IncrementingClockStub();
    var expectedStartDate = new DateTime(1980, 1, 1, 10, 5, 0);

    // Act & Assert
    for (int i = 0; i < 5; i++)
    {
        var currentTime = clock.Now;
        var expectedTime = expectedStartDate.AddSeconds(i * 5);
        
        Assert.Equal(expectedTime, currentTime, 
            $"Call {i + 1}: Expected {expectedTime}, but got {currentTime}");
}
