//
// TestWeaver Generated Tests
//
// Auto-generated by DeeperCore TestWeaver
// File: IClockTests.cs
// Generated: 2025-12-04T12:31:45.440801
//
// These tests cover edge cases and boundary conditions discovered
// through TestWeaver's 5-phase analysis methodology.
//

using System;

public class IClockTests
{
[Fact]
public void IncrementingClockStub_Now_IncrementsBy5SecondsEachCall()
{
    // Arrange
    var clock = new IncrementingClockStub();
    var expectedInitialDate = new DateTime(1980, 1, 1, 10, 5, 0);

    // Act & Assert
    for (int i = 0; i < 5; i++)
    {
        var currentTime = clock.Now;
        var expectedTime = expectedInitialDate.AddSeconds(i * 5);

        Assert.Equal(expectedTime, currentTime, 
            $"Call {i + 1}: Expected {expectedTime}, but got {currentTime}");
}
