//
// TestWeaver Generated Tests
//
// Auto-generated by DeeperCore TestWeaver
// File: IDelayProviderTests.cs
// Generated: 2025-12-04T12:31:45.436438
//
// These tests cover edge cases and boundary conditions discovered
// through TestWeaver's 5-phase analysis methodology.
//

using System;

public class IDelayProviderTests
{
[Fact]
public async Task DelayAsync_WithPositiveMilliseconds_ShouldDelayForSpecifiedTime()
{
    // Arrange
    var delayProvider = new DelayProvider();
    int delayMilliseconds = 100;
    var stopwatch = new System.Diagnostics.Stopwatch();

    // Act
    stopwatch.Start();
    await delayProvider.DelayAsync(delayMilliseconds);
    stopwatch.Stop();

    // Assert
    Assert.True(stopwatch.ElapsedMilliseconds >= delayMilliseconds, 
        $"The delay should be at least {delayMilliseconds} milliseconds, but it was {stopwatch.ElapsedMilliseconds} milliseconds.");

[Fact]
public async Task DelayAsync_WithZeroMilliseconds_CompletesImmediately()
{
    // Arrange
    var delayProvider = new DelayProvider();
    var stopwatch = new System.Diagnostics.Stopwatch();

    // Act
    stopwatch.Start();
    await delayProvider.DelayAsync(0);
    stopwatch.Stop();

    // Assert
    Assert.True(stopwatch.ElapsedMilliseconds < 10, $"Expected delay to complete almost immediately, but it took {stopwatch.ElapsedMilliseconds} ms");

[Fact]
public async Task DelayAsync_WithNonCancelledToken_CompleteAfterSpecifiedDelay()
{
    // Arrange
    var delayProvider = new DelayProvider();
    var delayTime = 100; // milliseconds
    var cts = new CancellationTokenSource();

    // Act
    var startTime = DateTime.UtcNow;
    await delayProvider.DelayAsync(delayTime, cts.Token);
    var endTime = DateTime.UtcNow;

    // Assert
    var actualDelay = endTime - startTime;
    Assert.True(actualDelay.TotalMilliseconds >= delayTime, 
        $"The delay should be at least {delayTime}ms, but it was {actualDelay.TotalMilliseconds}ms");

[Fact]
public async Task DelayAsync_WithVerySmallDelay_ShouldCompleteQuickly()
{
    // Arrange
    var delayProvider = new DelayProvider();
    var verySmallDelay = 1; // 1 millisecond
    var stopwatch = new System.Diagnostics.Stopwatch();

    // Act
    stopwatch.Start();
    await delayProvider.DelayAsync(verySmallDelay);
    stopwatch.Stop();

    // Assert
    Assert.True(stopwatch.ElapsedMilliseconds >= verySmallDelay, 
        $"The delay should be at least {verySmallDelay} milliseconds, but it was {stopwatch.ElapsedMilliseconds} milliseconds.");
    Assert.True(stopwatch.ElapsedMilliseconds < 100, 
        $"The delay should complete quickly, but it took {stopwatch.ElapsedMilliseconds} milliseconds.");

[Fact]
public async Task DelayAsync_WithAlreadyCanceledToken_ThrowsTaskCanceledException()
{
    // Arrange
    var delayProvider = new DelayProvider();
    var cts = new CancellationTokenSource();
    cts.Cancel(); // Cancel the token before calling DelayAsync

    // Act & Assert
    await Assert.ThrowsAsync<TaskCanceledException>(async () =>
    {
        await delayProvider.DelayAsync(1000, cts.Token);
    });
}
