//
// TestWeaver Generated Tests
//
// Auto-generated by DeeperCore TestWeaver
// File: IDelayProviderTests.cs
// Generated: 2025-12-04T13:50:26.298223
//
// These tests cover edge cases and boundary conditions discovered
// through TestWeaver's 5-phase analysis methodology.
//

using System;

public class IDelayProviderTests
{
[Fact]
public async Task DelayAsync_WithZeroMilliseconds_ShouldReturnImmediately()
{
    // Arrange
    var delayProvider = new DelayProvider();
    var stopwatch = new System.Diagnostics.Stopwatch();

    // Act
    stopwatch.Start();
    await delayProvider.DelayAsync(0);
    stopwatch.Stop();

    // Assert
    Assert.True(stopwatch.ElapsedMilliseconds < 10, $"Expected delay to complete immediately, but it took {stopwatch.ElapsedMilliseconds} ms");

[Fact]
public async Task DelayAsync_WithVerySmallDelay_ShouldCompleteQuickly()
{
    // Arrange
    var delayProvider = new DelayProvider();
    var stopwatch = new System.Diagnostics.Stopwatch();

    // Act
    stopwatch.Start();
    await delayProvider.DelayAsync(1);
    stopwatch.Stop();

    // Assert
    Assert.True(stopwatch.ElapsedMilliseconds < 10, $"The delay took {stopwatch.ElapsedMilliseconds}ms, which is longer than expected for a 1ms delay.");

[Fact]
public async Task DelayAsync_WithIntMaxValue_ShouldNotThrowException()
{
    // Arrange
    var delayProvider = new DelayProvider();
    var cts = new CancellationTokenSource(TimeSpan.FromMilliseconds(100)); // Set a short timeout

    // Act & Assert
    await Assert.ThrowsAnyAsync<OperationCanceledException>(async () =>
    {
        await delayProvider.DelayAsync(int.MaxValue, cts.Token);
    });

    Assert.True(cts.IsCancellationRequested, "The operation should have been canceled due to the timeout");

[Fact]
public async Task DelayAsync_WithCancellationToken_CompletesSuccessfully()
{
    // Arrange
    var delayProvider = new DelayProvider();
    var cts = new CancellationTokenSource();
    var delayTime = 100; // 100 milliseconds

    // Act
    var startTime = DateTime.UtcNow;
    await delayProvider.DelayAsync(delayTime, cts.Token);
    var endTime = DateTime.UtcNow;

    // Assert
    var elapsedTime = endTime - startTime;
    Assert.True(elapsedTime.TotalMilliseconds >= delayTime, 
        $"The delay should be at least {delayTime} milliseconds, but it was {elapsedTime.TotalMilliseconds} milliseconds.");
    Assert.False(cts.IsCancellationRequested, "The cancellation token should not have been requested.");
}
