//
// TestWeaver Generated Tests
//
// Auto-generated by DeeperCore TestWeaver
// File: ISpeedTestServiceTests.cs
// Generated: 2025-12-02T16:29:27.818828
//
// These tests cover edge cases and boundary conditions discovered
// through TestWeaver's 5-phase analysis methodology.
//

using System;

public class ISpeedTestServiceTests
{
[Fact]
public async Task GetServerLatencyAsync_WithVeryHighLatency_ReturnsExpectedResult()
{
    // Arrange
    var mockServer = new Mock<IServer>();
    var mockSpeedTestService = new Mock<ISpeedTestService>();
    var expectedLatency = 5000; // 5 seconds latency
    
    mockSpeedTestService
        .Setup(s => s.GetServerLatencyAsync(It.IsAny<IServer>(), It.IsAny<CancellationToken>()))
        .ReturnsAsync(new ServerLatencyResult(mockServer.Object, expectedLatency));

    // Act
    var result = await mockSpeedTestService.Object.GetServerLatencyAsync(mockServer.Object);

    // Assert
    Assert.NotNull(result);
    Assert.Equal(mockServer.Object, result.Server);
    Assert.Equal(expectedLatency, result.Latency);
    Assert.True(result.Latency >= 5000, "Latency should be very high (5000ms or more)");
}
