//
// TestWeaver Generated Tests
//
// Auto-generated by DeeperCore TestWeaver
// File: ISpeedTestServiceTests.cs
// Generated: 2025-12-04T12:31:45.437587
//
// These tests cover edge cases and boundary conditions discovered
// through TestWeaver's 5-phase analysis methodology.
//

using System;

public class ISpeedTestServiceTests
{
[Fact]
public async Task GetServersAsync_ReturnsEmptyArray_WhenNoServersAvailable()
{
    // Arrange
    var mockSpeedTestService = new Mock<ISpeedTestService>();
    mockSpeedTestService.Setup(s => s.GetServersAsync(It.IsAny<CancellationToken>()))
        .ReturnsAsync(Array.Empty<IServer>());

    // Act
    var result = await mockSpeedTestService.Object.GetServersAsync();

    // Assert
    Assert.NotNull(result);
    Assert.Empty(result);
    Assert.IsType<IServer[]>(result);

[Fact]
public async Task GetServersAsync_ShouldCancelOperation_WhenCancellationTokenIsTriggered()
{
    // Arrange
    var mockSpeedTestService = new Mock<ISpeedTestService>();
    var cts = new CancellationTokenSource();

    mockSpeedTestService
        .Setup(s => s.GetServersAsync(It.IsAny<CancellationToken>()))
        .Returns(async (CancellationToken ct) =>
        {
            await Task.Delay(1000, ct); // Simulate some work
            return new IServer[0];
        });

    // Act & Assert
    cts.CancelAfter(500); // Cancel after 500ms

    await Assert.ThrowsAsync<TaskCanceledException>(async () =>
    {
        await mockSpeedTestService.Object.GetServersAsync(cts.Token);
    });
}
