//
// TestWeaver Generated Tests
//
// Auto-generated by DeeperCore TestWeaver
// File: ISpeedTestServiceTests.cs
// Generated: 2025-12-03T22:12:44.173779
//
// These tests cover edge cases and boundary conditions discovered
// through TestWeaver's 5-phase analysis methodology.
//

using System;

public class ISpeedTestServiceTests
{
[Fact]
public async Task GetServersAsync_ConcurrentCalls_ReturnsUniqueResults()
{
    // Arrange
    var speedTestService = new Mock<ISpeedTestService>().Object;
    var tasks = new List<Task<IServer[]>>();
    var concurrentCalls = 5;

    // Act
    for (int i = 0; i < concurrentCalls; i++)
    {
        tasks.Add(speedTestService.GetServersAsync());

    var results = await Task.WhenAll(tasks);

    // Assert
    Assert.Equal(concurrentCalls, results.Length);
    for (int i = 0; i < results.Length; i++)
    {
        for (int j = i + 1; j < results.Length; j++)
        {
            Assert.NotSame(results[i], results[j], $"Results at index {i} and {j} should not be the same instance");
}
