//
// TestWeaver Generated Tests
//
// Auto-generated by DeeperCore TestWeaver
// File: SpeedTestTests.cs
// Generated: 2025-12-02T14:23:40.823437
//
// These tests cover edge cases and boundary conditions discovered
// through TestWeaver's 5-phase analysis methodology.
//

using System;

public class SpeedTestTests
{
[Fact]
public void CalculateSpeed_WithValidPositiveInputs_ReturnsCorrectSpeed()
{
    // Arrange
    var speedTestService = new SpeedTestService();
    double distance = 100.0; // 100 meters
    double time = 10.0; // 10 seconds

    // Act
    double speed = speedTestService.CalculateSpeed(distance, time);

    // Assert
    Assert.Equal(10.0, speed, 3); // Expected speed: 100m / 10s = 10 m/s, with 3 decimal places precision
    Assert.True(speed > 0, "Calculated speed should be positive");

[Fact]
public void CalculateSpeed_WithVerySmallTimeValue_ReturnsExpectedSpeed()
{
    // Arrange
    var speedTestService = new SpeedTestService();
    double distance = 1.0; // 1 meter
    double time = 0.000001; // 1 microsecond

    // Act
    double result = speedTestService.CalculateSpeed(distance, time);

    // Assert
    double expectedSpeed = 1000000; // 1 meter / 1 microsecond = 1,000,000 m/s
    Assert.Equal(expectedSpeed, result, 6); // Compare with 6 decimal places precision
    Assert.True(result > 0, "Speed should be positive for positive distance and time");

[Fact]
public void CalculateSpeed_WithVeryLargeValues_ReturnsCorrectSpeed()
{
    // Arrange
    var speedTestService = new SpeedTestService();
    double veryLargeDistance = 1e15; // 1 quadrillion
    double veryLargeTime = 1e12; // 1 trillion

    // Act
    double result = speedTestService.CalculateSpeed(veryLargeDistance, veryLargeTime);

    // Assert
    double expectedSpeed = 1000; // 1e15 / 1e12 = 1e3 = 1000
    Assert.Equal(expectedSpeed, result, 6); // Compare with 6 decimal places of precision
    Assert.True(result > 0, "Speed should be positive for positive distance and time");
    Assert.False(double.IsInfinity(result), "Result should not be infinity");
    Assert.False(double.IsNaN(result), "Result should not be NaN");
}
